sonar.projectKey=minhas-financas
sonar.projectName=Minhas Financas
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**,web/dist/**
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
